#!/usr/bin/env python3
"""Generate the Rootstead west blast-door surround as one opaque OBJ.

Units are Unreal centimetres, Z-up. The local origin is the opening's
base-centre. Place at world (-380, 0, 3500) with no rotation or scaling.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "SourceMesh" / "architecture"
MTL_NAME = "VD_BlastDoorSurround.mtl"
Vec3 = tuple[float, float, float]


@dataclass
class Mesh:
    name: str
    vertices: list[Vec3] = field(default_factory=list)
    faces: list[tuple[str, tuple[int, ...]]] = field(default_factory=list)

    def vertex(self, point: Vec3) -> int:
        self.vertices.append(point)
        return len(self.vertices)

    def face(self, material: str, indices: Iterable[int]) -> None:
        self.faces.append((material, tuple(indices)))

    def box(self, minimum: Vec3, maximum: Vec3, material: str) -> None:
        x0, y0, z0 = minimum
        x1, y1, z1 = maximum
        ids = [self.vertex((x, y, z)) for z in (z0, z1)
               for y in (y0, y1) for x in (x0, x1)]
        for face in ((0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1),
                     (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)):
            self.face(material, tuple(ids[index] for index in face))

    def cylinder(self, start: Vec3, end: Vec3, radius: float,
                 sides: int, material: str) -> None:
        delta = tuple(end[i] - start[i] for i in range(3))
        size = math.sqrt(sum(value * value for value in delta))
        axis = tuple(value / size for value in delta)
        seed = (0.0, 0.0, 1.0) if abs(axis[2]) < 0.92 else (1.0, 0.0, 0.0)
        side = (axis[1] * seed[2] - axis[2] * seed[1],
                axis[2] * seed[0] - axis[0] * seed[2],
                axis[0] * seed[1] - axis[1] * seed[0])
        side_size = math.sqrt(sum(value * value for value in side))
        side = tuple(value / side_size for value in side)
        up = (axis[1] * side[2] - axis[2] * side[1],
              axis[2] * side[0] - axis[0] * side[2],
              axis[0] * side[1] - axis[1] * side[0])
        rings: list[list[int]] = []
        for point in (start, end):
            ring = []
            for index in range(sides):
                angle = 2.0 * math.pi * index / sides
                ring.append(self.vertex((
                    point[0] + radius * (math.cos(angle) * side[0] + math.sin(angle) * up[0]),
                    point[1] + radius * (math.cos(angle) * side[1] + math.sin(angle) * up[1]),
                    point[2] + radius * (math.cos(angle) * side[2] + math.sin(angle) * up[2]),
                )))
            rings.append(ring)
        self.face(material, reversed(rings[0]))
        self.face(material, rings[1])
        for index in range(sides):
            following = (index + 1) % sides
            self.face(material, (rings[0][index], rings[0][following],
                                 rings[1][following], rings[1][index]))

    def prism_x(self, x0: float, x1: float, yz: list[tuple[float, float]],
                material: str) -> None:
        """Closed extrusion along X for coarse triangular gussets."""
        rings = [[self.vertex((x, y, z)) for y, z in yz] for x in (x0, x1)]
        self.face(material, reversed(rings[0]))
        self.face(material, rings[1])
        for index in range(len(yz)):
            following = (index + 1) % len(yz)
            self.face(material, (rings[0][index], rings[0][following],
                                 rings[1][following], rings[1][index]))

    def face_uvs(self, face: tuple[int, ...], scale: float = 100.0) -> list[tuple[float, float]]:
        points = [self.vertices[index - 1] for index in face]
        nx = ny = nz = 0.0
        for point, following in zip(points, points[1:] + points[:1]):
            nx += (point[1] - following[1]) * (point[2] + following[2])
            ny += (point[2] - following[2]) * (point[0] + following[0])
            nz += (point[0] - following[0]) * (point[1] + following[1])
        dominant = max(range(3), key=lambda i: abs((nx, ny, nz)[i]))
        if dominant == 0:
            return [(point[1] / scale, point[2] / scale) for point in points]
        if dominant == 1:
            return [(point[0] / scale, point[2] / scale) for point in points]
        return [(point[0] / scale, point[1] / scale) for point in points]

    def write_obj(self, path: Path) -> None:
        lines = ["# Generated by scripts/generate_blast_door_surround.py",
                 f"mtllib {MTL_NAME}", f"o {self.name}"]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        face_uv_indices: list[tuple[int, ...]] = []
        next_uv = 1
        for _, face in self.faces:
            uvs = self.face_uvs(face)
            lines.extend(f"vt {u:.6f} {v:.6f}" for u, v in uvs)
            face_uv_indices.append(tuple(range(next_uv, next_uv + len(uvs))))
            next_uv += len(uvs)
        current_material = None
        for (material, face), uv_indices in zip(self.faces, face_uv_indices):
            if material != current_material:
                lines.extend((f"usemtl {material}", "s 1"))
                current_material = material
            lines.append("f " + " ".join(
                f"{vertex}/{uv}" for vertex, uv in zip(face, uv_indices)))
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_surround() -> Mesh:
    mesh = Mesh("VD_BlastDoorSurround")
    concrete = "M_BlastSurround_CastConcrete"
    steel = "M_BlastSurround_AgedSteel"
    shadow = "M_BlastSurround_ShadowSteel"
    wear = "M_BlastSurround_HandWear"
    stain = "M_BlastSurround_WaterStain"
    bolt = "M_BlastSurround_BoltSteel"

    # Structural portal. World X -509..-350 becomes local X -129..30. The two
    # 100 cm-wide returns remain solid through the full 159 cm reveal depth.
    mesh.box((-129, -520, 0), (12, -400, 450), concrete)
    mesh.box((-129, 400, 0), (12, 520, 450), concrete)
    mesh.box((-129, -400, 392), (12, 400, 470), concrete)

    # Crude bolted east-face jacket: broad plate bands over the cast portal.
    mesh.box((12, -520, 0), (30, -400, 450), steel)
    mesh.box((12, 400, 0), (30, 520, 450), steel)
    mesh.box((12, -520, 392), (30, 520, 470), steel)

    # Deep reveal liners establish the bounded threshold and a dark continuous
    # shadow line. Inner faces stop exactly at Y +/-400, preserving the aperture.
    mesh.box((-125, -414, 8), (12, -400, 392), shadow)
    mesh.box((-125, 400, 8), (12, 414, 392), shadow)
    mesh.box((-125, -400, 378), (12, 400, 392), shadow)

    # Threshold plate spans the complete reveal and doorway. Low tread bars make
    # it read as hardware rather than a bare engine slab.
    mesh.box((-129, -400, 0), (30, 400, 8), wear)
    for x in (-112, -76, -40, -4, 28):
        mesh.box((x - 2.5, -396, 8), (x + 2.5, 396, 11), steel)

    # Existing leaves remain separate. This exposed track and trolley hardware
    # sits above their 392 cm top envelope and outside their animation ownership.
    mesh.box((18, -395, 365), (46, 395, 390), shadow)
    mesh.box((34, -392, 372), (52, 392, 384), steel)
    for y in (-255, 255):
        mesh.box((20, y - 38, 355), (50, y + 38, 405), steel)
        mesh.cylinder((14, y, 379), (54, y, 379), 11, 12, bolt)

    # Three coarse hinge/guide shoes per jamb. Oversized pins and triangular head
    # gussets keep the silhouette older and heavier than the glazed vestibule.
    for side_y in (-1, 1):
        inner = 400 * side_y
        outer = 448 * side_y
        y0, y1 = sorted((inner, outer))
        for z in (82, 202, 322):
            mesh.box((18, y0, z - 24), (48, y1, z + 24), steel)
            mesh.cylinder((33, inner + 12 * side_y, z - 30),
                          (33, inner + 12 * side_y, z + 30), 10, 12, bolt)
        yz: list[tuple[float, float]]
        if side_y < 0:
            yz = [(-400.0, 392.0), (-400.0, 450.0), (-468.0, 450.0)]
        else:
            yz = [(400.0, 392.0), (468.0, 450.0), (400.0, 450.0)]
        mesh.prism_x(30, 48, yz, steel)

    # Large, irregular-but-authored bolting grid on the east jacket.
    for y in (-486, -434, 434, 486):
        for z in (38, 128, 218, 308, 398, 438):
            mesh.cylinder((30, y, z), (38, y, z), 5.5, 10, bolt)
    for y in (-360, -240, -120, 0, 120, 240, 360):
        for z in (414, 452):
            mesh.cylinder((30, y, z), (38, y, z), 5.5, 10, bolt)

    # Replaceable hand-height rub plates on the inner jamb faces. They are
    # intentionally asymmetric: the north plate has been replaced more recently.
    mesh.box((-72, -400, 102), (18, -394, 188), wear)
    mesh.box((-48, 394, 112), (18, 400, 205), wear)
    for x, y, z in ((-61, -391, 114), (7, -391, 176),
                    (-37, 391, 124), (7, 391, 193)):
        mesh.cylinder((x, y, z), (x, y + (6 if y < 0 else -6), z), 3.8, 8, bolt)

    # Mineral/water staining is separated into semantic slots for material swaps.
    # Thin plates lie on the west cast face and continue below the sill datum;
    # the negative-Z apron is intentional because the pivot remains at the
    # opening base rather than at the mesh's lowest decorative point.
    mesh.box((-132, -320, -48), (-129, 320, 0), stain)
    mesh.box((-132, -505, 0), (-129, -430, 104), stain)
    mesh.box((-132, 442, 0), (-129, 505, 76), stain)
    mesh.box((-132, -318, 392), (-129, -272, 452), stain)
    mesh.box((-132, 126, 392), (-129, 174, 436), stain)

    return mesh


def write_mtl() -> None:
    materials = {
        "M_BlastSurround_CastConcrete": ((0.29, 0.30, 0.27), 0.88),
        "M_BlastSurround_AgedSteel": ((0.18, 0.23, 0.22), 0.72),
        "M_BlastSurround_ShadowSteel": ((0.055, 0.065, 0.062), 0.82),
        "M_BlastSurround_HandWear": ((0.34, 0.35, 0.31), 0.56),
        "M_BlastSurround_WaterStain": ((0.16, 0.19, 0.16), 0.94),
        "M_BlastSurround_BoltSteel": ((0.38, 0.39, 0.34), 0.48),
    }
    lines = ["# Semantic preview materials for VD_BlastDoorSurround"]
    for name, (color, roughness) in materials.items():
        lines.extend((f"newmtl {name}",
                      f"Kd {color[0]:.3f} {color[1]:.3f} {color[2]:.3f}",
                      f"Pr {roughness:.3f}", "illum 2", ""))
    (OUT / MTL_NAME).write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    mesh = build_surround()
    mesh.write_obj(OUT / f"{mesh.name}.obj")
    write_mtl()
    print(f"wrote {mesh.name}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")


if __name__ == "__main__":
    main()
